# Generated by Django 2.2 on 2019-06-18 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_userproject_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproject',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='restapi.Project'),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
