# Generated by Django 2.2 on 2019-06-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_auto_20190619_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectroles',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
